apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-secrets
  namespace: shopsphere-staging
type: Opaque
stringData:
  database-url: "postgresql://postgres:YOUR_PASSWORD@db.yvrlcocfshgkabzxluxn.supabase.co:5432/postgres?sslmode=require"
  jwt-secret: "CHANGE_ME"
